name = "SatSolver"
uuid = "c4752cc9-fe37-4e66-9e7b-290ad5257808"
authors = ["Tung Anh Vu <vu.tunganh96@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
